version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: docker/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HTTP_ADDRESS=:8080
      - GRPC_ADDRESS=:9090
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_ADDRESS=redis:6379
      - STORAGE_BASE_PATH=/data
      - STORAGE_UPLOAD_PATH=/data/uploads
      - STORAGE_PROCESSED_PATH=/data/processed
      - STORAGE_BASE_URL=http://localhost:8080/media
      - SERVICE_PROCESSING_ADDRESS=stream-processor:9091
    volumes:
      - video-storage:/data
    depends_on:
      - kafka
      - redis
      - stream-processor
    networks:
      - app-network

  stream-ingestor:
    build:
      context: .
      dockerfile: docker/stream-ingestor/Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_ADDRESS=redis:6379
      - STORAGE_BASE_PATH=/data
      - STORAGE_UPLOAD_PATH=/data/uploads
    volumes:
      - video-storage:/data
    depends_on:
      - kafka
      - redis
    networks:
      - app-network

  stream-processor:
    build:
      context: .
      dockerfile: docker/stream-processor/Dockerfile
    environment:
      - GRPC_ADDRESS=:9091
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_ADDRESS=redis:6379
      - STORAGE_BASE_PATH=/data
      - STORAGE_PROCESSED_PATH=/data/processed
      - STORAGE_BASE_URL=http://localhost:8080/media
    volumes:
      - video-storage:/data
    depends_on:
      - kafka
      - redis
    networks:
      - app-network

  # Infrastructure services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - app-network

  # For development/testing only
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  redis-data:
  video-storage:

networks:
  app-network:
    driver: bridge